### ISSUE TITLE
`> 8` or `> 7` ? :)

### ISSUE THREAD

**Issue by phrawzty** [martyndavies/ag-mixes-example#1]
Hello! The [README](https://github.com/martyndavies/ag-mixes-example/blame/master/README.md#L20) says:
> most fire mixes, rated 8 or higher

But the code says: https://github.com/martyndavies/ag-mixes-example/blob/e42b9ff5241feb7b5ffdf063d6a9778b1add7bdf/js/scripts.js#L158

So:
![image](https://user-images.githubusercontent.com/625232/31881501-f8c37c60-b7e3-11e7-9af8-62c64116cf4a.png)

It's a nit, but there you go. 😉 

Great project btw. I really enjoyed spending some time listening to, well, whatever it is the kids listen to these days. 👴

**Comment by martyndavies** [comment]
Absolutely true! NOW 8 is included.
